spring:
    application:
        name: proto-microservice
        description: Microservice with protobuf encoded response.

server:
    port: ${port:8010}
    compression:
            enabled: true
            min-response-size: 1
